#include "CrystalControl.h"

#include <stdlib.h>
#include <pthread.h>
#include <inttypes.h>
#include <time.h>
#include <string.h>

#include "root_directory.h" // This is a configuration file generated by CMake.

#define DEFAULT_SPEED 10

struct crystal_control_t
{
  unsigned _number;
  CrystalModel *_cm;
  CrystalView *_cv;

  GtkWidget *_main_app_window;
  
  volatile int _sim_running;
  pthread_t _thread;
};

static unsigned
CrystalControl_request_new_modifier(CrystalControl *self);
static void
signal_stop_simulation(CrystalControl *self);
static void *
run_thread(void *arg);
static gboolean
run_some_steps(gpointer data);

static double
get_time() {
  struct timespec t;
  clock_gettime(CLOCK_REALTIME, &t);
  return t.tv_sec + t.tv_nsec/1e9;
}

CrystalControl *
CrystalControl_create(CrystalModel *cm,
		      CrystalView *cv)
{
  CrystalControl *self = (CrystalControl *) calloc(1, sizeof(CrystalControl));
  self->_cm = cm;
  self->_cv = cv;

  self->_number = DEFAULT_SPEED;
  return self;
}

void
CrystalControl_destroy(CrystalControl *self)
{
  if (!self) { return; }
  
  signal_stop_simulation(self);
  free(self);
}

static void
show_error_message(GtkWindow *parent, char const *msg)
{
  GtkWidget *dialog = gtk_message_dialog_new(parent,
					     GTK_DIALOG_DESTROY_WITH_PARENT,
					     GTK_MESSAGE_WARNING,
					     GTK_BUTTONS_OK,
					     msg, NULL);
  gtk_dialog_run(GTK_DIALOG(dialog));
  gtk_widget_destroy(dialog);
}

static unsigned
CrystalControl_request_new_modifier(CrystalControl *self)
{
  unsigned new_speed;
  int input_accepted, result, _new_speed;
  GtkDialogFlags flags = GTK_DIALOG_MODAL | GTK_DIALOG_DESTROY_WITH_PARENT;
  GtkWidget *dialog = gtk_dialog_new_with_buttons("Change Speed",
						  GTK_WINDOW(self->_main_app_window),
						  flags,
						  ("OK"), GTK_RESPONSE_ACCEPT,
						  ("Cancel"), GTK_RESPONSE_REJECT,
						  NULL);
  GtkWidget *dialog_content = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);
  GtkWidget *new_mod_tf = gtk_entry_new();
  
  gtk_entry_set_input_purpose(GTK_ENTRY(new_mod_tf), GTK_INPUT_PURPOSE_DIGITS);
  gtk_box_pack_start(GTK_BOX(dialog_content),
		     gtk_label_new("Enter a new speed:"),
		     FALSE, FALSE, 0);
  gtk_box_pack_start(GTK_BOX(dialog_content),
		     new_mod_tf,
		     FALSE, FALSE, 0);

  gtk_container_add(GTK_CONTAINER(gtk_dialog_get_content_area(GTK_DIALOG(dialog))),
		    dialog_content);
  gtk_widget_show_all(dialog);
  
  new_speed = 0;
  for (input_accepted = 0; !input_accepted;) {
    result = gtk_dialog_run(GTK_DIALOG(dialog));
    if (result == GTK_RESPONSE_ACCEPT) {
      if (gtk_entry_get_text_length(GTK_ENTRY(new_mod_tf)) > 0) {
	_new_speed = atoll(gtk_entry_get_text(GTK_ENTRY(new_mod_tf)));
	if (_new_speed > 0) {
	  new_speed = _new_speed;
	  input_accepted = 1;
	} else {
	  show_error_message(GTK_WINDOW(self->_main_app_window),
			     "New value must a positive integer.");
	  gtk_entry_set_text(GTK_ENTRY(new_mod_tf), "");
	}
      }
    } else {
      input_accepted = 1;
    }
  }
  gtk_widget_destroy(dialog);
  return new_speed;
}

static void
signal_stop_simulation(CrystalControl *self)
{
  if (self->_sim_running) {
    self->_sim_running = 0;
  }
  pthread_join(self->_thread, NULL);
}

static void *
run_thread(void *arg)
{
  double t0, t1;
  CrystalControl *self = (CrystalControl *)arg;

  t0 = get_time();
  while (self->_sim_running) {
    if (!CrystalModel_run_some_steps(self->_cm, self->_number)) {
      self->_sim_running = 0;
    }
    g_timeout_add(0, run_some_steps, self);
  }
  t1 = get_time();
  printf("C Simulation took %.3f s\n", t1-t0);
  return NULL;
}

static gboolean
run_some_steps(gpointer data)
{
  CrystalView_repaint(((CrystalControl *)data)->_cv);
  return FALSE; // run once
}

static gboolean
change_speed_event_cb(GtkWidget *widget,
		      gpointer data)
{
  CrystalControl *self;
  unsigned modifier;
  (void)widget;
  
  if (!data) {
    return FALSE;
  }
  
  self = (CrystalControl *) data;
  signal_stop_simulation(self);
  
  modifier = CrystalControl_request_new_modifier(self);
  if (modifier > 0) {
    self->_number = modifier;
  }
  return TRUE;
}

static gboolean
start_event_cb(GtkWidget *widget,
	       gpointer data)
{
  CrystalControl *self;
  (void)widget;
  
  if (!data) {
    return FALSE;
  }
  
  self = (CrystalControl *) data;
  signal_stop_simulation(self);
  
  CrystalModel_reset(self->_cm);
  CrystalView_repaint(self->_cv);
  
  if (!self->_sim_running) {
    //CrystalModel_srand(self->_cm, time(NULL));
    CrystalModel_srand(self->_cm, 0);
    self->_sim_running = 1;
    pthread_create(&self->_thread, NULL, run_thread, self);
  }
  return TRUE;
}


static gboolean
stop_event_cb(GtkWidget *widget,
	      gpointer data)
{
  (void)widget;
  if (!data) { return FALSE; }
  
  signal_stop_simulation((CrystalControl *)data);
  return TRUE;
}

void
CrystalControl_init_ui(CrystalControl *self,
		       GtkBuilder *builder)
{
  GtkWidget *start_btn, *stop_btn, *change_speed_btn;
  
  CrystalView_set_gtk_widget(self->_cv, GTK_WIDGET(gtk_builder_get_object(builder, "bath")));
  
  start_btn = GTK_WIDGET(gtk_builder_get_object(builder, "start_btn"));
  g_signal_connect(start_btn, "clicked", G_CALLBACK(start_event_cb), self);
  stop_btn = GTK_WIDGET(gtk_builder_get_object(builder, "stop_btn"));
  g_signal_connect(stop_btn, "clicked", G_CALLBACK(stop_event_cb), self);
  change_speed_btn = GTK_WIDGET(gtk_builder_get_object(builder, "chspeed_btn"));
  g_signal_connect(change_speed_btn, "clicked", G_CALLBACK(change_speed_event_cb), self);

  self->_main_app_window = GTK_WIDGET(gtk_builder_get_object(builder, "app-window"));
}
